apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: exam
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "af710c9ff2fa94811bf8e17a3a490fa1-1054419295.us-east-2.elb.amazonaws.com"
      secretName: examportal-tls
  rules:
    - host: "af710c9ff2fa94811bf8e17a3a490fa1-1054419295.us-east-2.elb.amazonaws.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-svc
                port:
                  number: 3000

