kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dash-pvc
  namespace: dash2
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
