kind: PersistentVolume
apiVersion: v1
metadata:
  name: dash-pv
  namespace: dash2
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: '/tmp/sim-data'
