apiVersion: v1
kind: Secret
metadata:
  name: dash-secret
  namespace: dash
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: TWFkaHVANTU1  # "secret" in Base64
  MONGO_INITDB_ROOT_USERNAME: bWFkaHU=  # "mongoadmin" in Base64
